"""Add SystemConfig and ApiUsageLog

Revision ID: b99205d2bc7b
Revises: 006_backfill_draft_intelligence
Create Date: 2026-03-22 10:12:39.932794+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99205d2bc7b'
down_revision: Union[str, None] = '006_backfill_draft_intelligence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
